[project]
name = "hasura-chris-poc"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Jennings Zhang", email = "dev@sl.jennin.xyz" }
]
dependencies = [
    "fastapi>=0.111.1",
    "aiochris==0.5.0a6",
    "yarl>=1.9.4",
]
readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []
virtual = true

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/hasura_chris_poc"]
